[tools]
go = "1.26"
"go:github.com/99designs/gqlgen" = "0.17.86"
"go:github.com/golangci/golangci-lint/v2/cmd/golangci-lint" = "v2.9.0"
"go:github.com/nametake/golangci-lint-langserver" = "0.0.11"
golangci-lint-langserver = "0.0.11"
